### ISSUE TITLE
Change build??

### ISSUE THREAD

**Issue by muleyau** [KillerKei/UnityRP-Report-System-ESX-#1]
![image](https://github.com/KillerKei/UnityRP-Report-System-ESX-/assets/147155513/490dd0ff-92fd-420c-b703-7cfc7f927ff8)
no idea how im meant to change to a production build of vue? i've never touched vue in my life so not sure what im lookin at

**Comment by muleyau** [comment]
alright i fixed that issue but as soon as i ensure the script the admin menu pops up but i cant interact with the ui?
it doesnt seem like a command is linked to the admin menu from what i can see. would that be why?

**Comment by KillerKei** [comment]
Check Discord DMs.

**Comment by KillerKei** [comment]
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script> line 11 of tickets.html
